Create ODropDown for OLanguage component.
a2insights/octo-app pull request #11
Opened 2021-04-21 03:43 UTC by AleksanderClay

2021-04-21 03:47 UTC, Atiladanvi commented
@AleksanderClay Vamos mudar o título da pr e fazer isso para todos os compoenents dropdowns ?

2021-04-22 02:09 UTC, Atiladanvi requested changes
Implementar essa configuração no store de settings assim como outras modificações nos comenttários.

2021-04-22 02:09 UTC, Atiladanvi commented on ui/src/components/OLanguageOptions/ODropDownLanguage.vue
> +<template>
a organização fica assim: ui/src/components/dropdowns/ODropdownLanguage

2021-04-22 02:09 UTC, Atiladanvi commented on ui/src/components/OLanguageOptions/ODropDownLanguage.vue
> +      <q-list dense>
Vamos criar um helper pra retornar a lista de linguagens lendo diretamente isso no arquivo index da tradução. Assim só aparecerá as langs que estão implementadas. Deve ter como ver isso pelo container do quasar. Só verificar a api.

2021-04-22 19:25 UTC, AleksanderClay commented on ui/src/components/OLanguageOptions/ODropDownLanguage.vue
> +<template>
Ok.

2021-04-22 19:42 UTC, AleksanderClay commented on ui/src/components/OLanguageOptions/ODropDownLanguage.vue
> +      <q-list dense>
Ok

2021-04-25 02:28 UTC, Atiladanvi commented
LGTM !

2021-04-25 02:28 UTC, merged